version: 2
updates:
  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: "weekly"
      day: saturday
    commit-message:
      prefix: "chore(deps)"

  - package-ecosystem: "docker"
    directory: "/.devcontainer"
    schedule:
      interval: "weekly"
      day: saturday
    commit-message:
      prefix: "chore(deps)"
